---
# - name: "Load extra variables"
#   include_vars:
#     file: vars/helloworldvars.yml

# - name: "HelloWorld"
#   shell: echo 'Hello World'
#   register: printout #if you want to use the print in task, use with stdout, if you want to use from the vars, comment this one and user it in msg without stdout

#------------------------------
- name: "{{ item }} 1 is {{ roletype }} and it is starting"
  include_tasks: "{{ item }}.yml"
  #debug:
  #  msg: "{{ item }}"
  #when: (rolenum == 'role1' and ansible_distribution == "Ubuntu")
  when: item == 'role1' and roletype == 'even' #does not need any brackets
  #when: rolenum == 'role1' and roletype == 'even' #does not need any brackets

  loop: "{{ rolenum|flatten(levels=1) }}"
  #with_items: "{{ rolenum }}"


- name: "{{ item }} 2 is {{ roletype }} and it is starting"
  include_tasks: "{{ item }}.yml"
  #debug:
  #  msg: "{{ item }}"
  #when: (rolenum == 'role2' and ansible_distribution == "Ubuntu")
  when: item == 'role2' and roletype == 'odd' #does not need any brackets
  #when: rolenum == 'role2' and roletype == 'odd' #does not need any brackets
  loop: "{{ rolenum|flatten(levels=1) }}"
  #with_items: "{{ rolenum }}"
    #msg: "{{ printout.stdout }}, my name is: {{ inventory_hostname }} and this system is up for: {{ currentuptime.stdout }} "


    # msg: "Hello, my name is: {{ currenthost }}"
    # msg: "System {{ inventory_hostname }} has uuid {{ ansible_product_uuid }}"
    # msg: "Current uptime is: {{ currentuptime }}"
    # msg: "System {{ uptime2 }} "

